/**
 * Invoice Service
 *
 * Generates invoice records in the `invoices` table and emails a formatted
 * HTML receipt to the school's billing contact.
 *
 * Called:
 *  - Automatically from webhooks.ts after every successful payment
 *  - On-demand from schools.ts (GET /schools/me/invoices/:id/resend)
 */

import { query, getClient } from '../database/connection';
import { emailService } from './emailService';

export interface GenerateInvoiceOptions {
  schoolId: string;
  billingEventId?: string; // optional: link invoice to a specific billing_event row
  amountPaid: number;
  currency: string;
  planName: string;
  billingPeriod: 'monthly' | 'yearly';
  gatewayInvoiceId?: string; // Stripe/Razorpay invoice/payment id
  periodStart?: Date;
  periodEnd?: Date;
}

export class InvoiceService {
  /**
   * Create an invoice record and fire the receipt email.
   * Returns the new invoice row.
   */
  async generateInvoice(opts: GenerateInvoiceOptions): Promise<any> {
    // 1. Fetch school details for the email
    const schoolResult = await query(
      `SELECT name, email, address, city, state, country, currency FROM schools WHERE id = $1`,
      [opts.schoolId]
    );
    if (schoolResult.rows.length === 0) throw new Error('School not found');
    const school = schoolResult.rows[0];

    const currency = opts.currency || school.currency || 'INR';
    const taxRate  = currency === 'INR' ? 0.18 : 0; // 18% GST for India
    const taxAmount   = parseFloat((opts.amountPaid * taxRate).toFixed(2));
    const totalAmount = parseFloat((opts.amountPaid + taxAmount).toFixed(2));

    // Period defaults
    const periodStart = opts.periodStart || new Date();
    const periodEnd   = opts.periodEnd   || (() => {
      const d = new Date(periodStart);
      d.setDate(d.getDate() + (opts.billingPeriod === 'yearly' ? 365 : 30));
      return d;
    })();

    // 2. Insert invoice row (invoice_number generated by DB function)
    const client = await getClient();
    let invoice: any;
    try {
      await client.query('BEGIN');

      const result = await client.query(
        `INSERT INTO invoices
           (school_id, invoice_number, amount, tax_amount, total_amount, currency,
            plan_name, billing_period, period_start, period_end,
            status, due_date, paid_at, gateway_invoice_id)
         VALUES
           ($1, generate_invoice_number(), $2, $3, $4, $5,
            $6, $7, $8, $9,
            'paid', $10, NOW(), $11)
         RETURNING *`,
        [
          opts.schoolId,
          opts.amountPaid,
          taxAmount,
          totalAmount,
          currency,
          opts.planName,
          opts.billingPeriod,
          periodStart,
          periodEnd,
          periodEnd,               // due_date = period_end
          opts.gatewayInvoiceId || null,
        ]
      );

      invoice = result.rows[0];
      await client.query('COMMIT');
    } catch (err) {
      await client.query('ROLLBACK');
      throw err;
    } finally {
      client.release();
    }

    // 3. Send receipt email (non-blocking — never throws on email failure)
    this.sendReceiptEmail(school, invoice).catch(err =>
      console.error('[InvoiceService] Receipt email failed:', err)
    );

    return invoice;
  }

  /** Re-send receipt for an existing invoice */
  async resendReceipt(invoiceId: string, schoolId: string): Promise<void> {
    const result = await query(
      `SELECT i.*, s.name AS school_name, s.email AS school_email,
              s.address, s.city, s.state, s.country
       FROM invoices i JOIN schools s ON s.id = i.school_id
       WHERE i.id = $1 AND i.school_id = $2`,
      [invoiceId, schoolId]
    );
    if (result.rows.length === 0) throw new Error('Invoice not found');

    const row = result.rows[0];
    const school = {
      name:    row.school_name,
      email:   row.school_email,
      address: row.address,
      city:    row.city,
      state:   row.state,
      country: row.country,
    };
    await this.sendReceiptEmail(school, row);
  }

  // ─── Private helpers ────────────────────────────────────────

  private async sendReceiptEmail(school: any, invoice: any): Promise<void> {
    const appName = process.env.APP_NAME || 'EduSaaS';
    const currency = invoice.currency || 'INR';
    const fmt = (n: number) =>
      currency === 'INR'
        ? `₹${Number(n).toLocaleString('en-IN', { minimumFractionDigits: 2 })}`
        : `${currency} ${Number(n).toFixed(2)}`;

    const periodStr = `${fmtDate(invoice.period_start)} – ${fmtDate(invoice.period_end)}`;
    const subject   = `Payment receipt – ${invoice.invoice_number} | ${appName}`;

    const html = `
<!DOCTYPE html><html><head>
<style>
  body{font-family:Arial,sans-serif;line-height:1.6;color:#333;margin:0;padding:0}
  .wrap{max-width:620px;margin:0 auto;padding:20px}
  .header{background:linear-gradient(135deg,#4f46e5,#6366f1);color:white;padding:28px 32px;border-radius:12px 12px 0 0}
  .header h1{margin:0;font-size:22px}
  .header p{margin:4px 0 0;opacity:.85;font-size:14px}
  .body{background:#f8fafc;padding:28px 32px;border-radius:0 0 12px 12px}
  .badge{display:inline-block;background:#dcfce7;color:#16a34a;padding:4px 12px;border-radius:20px;font-size:12px;font-weight:600;margin-bottom:16px}
  table{width:100%;border-collapse:collapse;margin:16px 0}
  th{text-align:left;padding:10px 12px;background:#e2e8f0;font-size:13px;color:#475569}
  td{padding:10px 12px;border-bottom:1px solid #e2e8f0;font-size:14px}
  .total-row td{font-weight:700;background:#f1f5f9;font-size:15px}
  .school-box{background:white;border:1px solid #e2e8f0;border-radius:8px;padding:14px 18px;margin-top:20px;font-size:13px;color:#475569}
  .footer{text-align:center;margin-top:20px;font-size:12px;color:#94a3b8}
</style>
</head><body><div class="wrap">
  <div class="header">
    <h1>${appName}</h1>
    <p>Payment Receipt</p>
  </div>
  <div class="body">
    <div class="badge">PAID</div>
    <p>Hi ${school.name},<br>Thank you for your payment. Here is your receipt.</p>

    <table>
      <tr><th>Invoice #</th><td>${invoice.invoice_number}</td></tr>
      <tr><th>Date</th><td>${fmtDate(invoice.paid_at || invoice.created_at)}</td></tr>
      <tr><th>Plan</th><td>${capitalize(invoice.plan_name)} (${invoice.billing_period})</td></tr>
      <tr><th>Period</th><td>${periodStr}</td></tr>
    </table>

    <table>
      <tr><th>Description</th><th style="text-align:right">Amount</th></tr>
      <tr>
        <td>${capitalize(invoice.plan_name)} Plan – ${capitalize(invoice.billing_period)} subscription</td>
        <td style="text-align:right">${fmt(invoice.amount)}</td>
      </tr>
      ${Number(invoice.tax_amount) > 0 ? `
      <tr>
        <td>GST (18%)</td>
        <td style="text-align:right">${fmt(invoice.tax_amount)}</td>
      </tr>` : ''}
      <tr class="total-row">
        <td>Total Paid</td>
        <td style="text-align:right">${fmt(invoice.total_amount)}</td>
      </tr>
    </table>

    <div class="school-box">
      <strong>Billed to:</strong><br>
      ${school.name}<br>
      ${[school.address, school.city, school.state, school.country].filter(Boolean).join(', ')}
    </div>

    <p style="margin-top:20px;font-size:13px;color:#64748b">
      Keep this email as your official receipt. For billing queries write to
      <a href="mailto:billing@edusaas.in">billing@edusaas.in</a>.
    </p>
  </div>
  <div class="footer">© ${new Date().getFullYear()} ${appName}. All rights reserved.</div>
</div></body></html>`;

    await emailService.sendEmail({ to: school.email, subject, html });
  }
}

// ─── Tiny helpers ────────────────────────────────────────────

function fmtDate(d: Date | string | null): string {
  if (!d) return '—';
  return new Date(d).toLocaleDateString('en-IN', {
    day: '2-digit', month: 'short', year: 'numeric',
  });
}

function capitalize(s: string): string {
  if (!s) return '';
  return s.charAt(0).toUpperCase() + s.slice(1);
}

export const invoiceService = new InvoiceService();
