/**
 * Invoice Service
 *
 * Generates invoice records in the `invoices` table and emails a formatted
 * HTML receipt to the school's billing contact.
 *
 * Called:
 *  - Automatically from webhooks.ts after every successful payment
 *  - On-demand from schools.ts (GET /schools/me/invoices/:id/resend)
 */

import { query, getClient } from "../database/connection";
import { emailService } from "./emailService";
import puppeteer from "puppeteer";
import path from "path";
import fs from "fs";

export interface GenerateInvoiceOptions {
  schoolId: string;
  billingEventId?: string; // optional: link invoice to a specific billing_event row
  amountPaid: number;
  currency: string;
  planName: string;
  billingPeriod: "monthly" | "yearly";
  gatewayInvoiceId?: string; // Stripe/Razorpay invoice/payment id
  periodStart?: Date;
  periodEnd?: Date;
}

export class InvoiceService {
  private readonly pdfDir = path.join(process.cwd(), "uploads", "invoices");

  constructor() {
    if (!fs.existsSync(this.pdfDir)) {
      fs.mkdirSync(this.pdfDir, { recursive: true });
    }
  }

  /**
   * Create an invoice record and fire the receipt email.
   * Returns the new invoice row.
   */
  async generateInvoice(opts: GenerateInvoiceOptions): Promise<any> {
    // 1. Fetch school details for the email
    const schoolResult = await query(
      `SELECT name, email, address, city, state, country, currency, gstin FROM schools WHERE id = $1`,
      [opts.schoolId],
    );
    if (schoolResult.rows.length === 0) throw new Error("School not found");
    const school = schoolResult.rows[0];

    const currency = opts.currency || school.currency || "INR";
    const taxRate = currency === "INR" ? 0.18 : 0; // 18% GST for India
    const taxAmount = parseFloat((opts.amountPaid * taxRate).toFixed(2));
    const totalAmount = parseFloat((opts.amountPaid + taxAmount).toFixed(2));

    // Period defaults
    const periodStart = opts.periodStart || new Date();
    const periodEnd =
      opts.periodEnd ||
      (() => {
        const d = new Date(periodStart);
        d.setDate(d.getDate() + (opts.billingPeriod === "yearly" ? 365 : 30));
        return d;
      })();

    // 2. Insert invoice row (invoice_number generated by DB function)
    const client = await getClient(opts.schoolId);
    let invoice: any;
    try {
      await client.query("BEGIN");

      const result = await client.query(
        `INSERT INTO invoices
           (school_id, invoice_number, amount, tax_amount, total_amount, currency,
            plan_name, billing_period, period_start, period_end,
            status, due_date, paid_at, gateway_invoice_id)
         VALUES
           ($1, generate_invoice_number(), $2, $3, $4, $5,
            $6, $7, $8, $9,
            'paid', $10, NOW(), $11)
         RETURNING *`,
        [
          opts.schoolId,
          opts.amountPaid,
          taxAmount,
          totalAmount,
          currency,
          opts.planName,
          opts.billingPeriod,
          periodStart,
          periodEnd,
          periodEnd, // due_date = period_end
          opts.gatewayInvoiceId || null,
        ],
      );

      invoice = result.rows[0];
      await client.query("COMMIT");
    } catch (err) {
      await client.query("ROLLBACK");
      throw err;
    } finally {
      client.release();
    }

    // 3. Generate PDF invoice (non-blocking)
    this.generatePDFInvoice(school, invoice)
      .then((pdfUrl) => {
        if (pdfUrl) {
          query("UPDATE invoices SET pdf_url = $1 WHERE id = $2", [
            pdfUrl,
            invoice.id,
          ]).catch((err) =>
            console.error("[InvoiceService] Failed to update pdf_url:", err),
          );
        }
      })
      .catch((err) =>
        console.error("[InvoiceService] PDF generation failed:", err),
      );

    // 4. Send receipt email (non-blocking — never throws on email failure)
    this.sendReceiptEmail(school, invoice).catch((err) =>
      console.error("[InvoiceService] Receipt email failed:", err),
    );

    return invoice;
  }

  /** Re-send receipt for an existing invoice */
  async resendReceipt(invoiceId: string, schoolId: string): Promise<void> {
    const result = await query(
      `SELECT i.*, s.name AS school_name, s.email AS school_email,
              s.address, s.city, s.state, s.country, s.gstin
       FROM invoices i JOIN schools s ON s.id = i.school_id
       WHERE i.id = $1 AND i.school_id = $2`,
      [invoiceId, schoolId],
    );
    if (result.rows.length === 0) throw new Error("Invoice not found");

    const row = result.rows[0];
    const school = {
      name: row.school_name,
      email: row.school_email,
      address: row.address,
      city: row.city,
      state: row.state,
      country: row.country,
      gstin: row.gstin,
    };

    // Regenerate PDF if missing
    if (!row.pdf_url) {
      const pdfUrl = await this.generatePDFInvoice(school, row);
      if (pdfUrl) {
        await query("UPDATE invoices SET pdf_url = $1 WHERE id = $2", [
          pdfUrl,
          invoiceId,
        ]);
      }
    }

    await this.sendReceiptEmail(school, row);
  }

  /** Generate a GST-compliant PDF invoice */
  private async generatePDFInvoice(
    school: any,
    invoice: any,
  ): Promise<string | null> {
    const appName = process.env.APP_NAME || "EduSaaS";
    const appUrl = process.env.APP_URL || "https://edusaas.in";
    const currency = invoice.currency || "INR";
    const fmt = (n: number) =>
      currency === "INR"
        ? `₹${Number(n).toLocaleString("en-IN", { minimumFractionDigits: 2 })}`
        : `${currency} ${Number(n).toFixed(2)}`;

    const periodStr = `${fmtDate(invoice.period_start)} – ${fmtDate(invoice.period_end)}`;
    const invoiceDate = fmtDate(invoice.paid_at || invoice.created_at);

    const html = `
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: 'Helvetica Neue', Arial, sans-serif; font-size: 12px; color: #1e293b; line-height: 1.5; }
  .page { padding: 40px; }
  .header { display: flex; justify-content: space-between; align-items: flex-start; border-bottom: 2px solid #4f46e5; padding-bottom: 20px; margin-bottom: 30px; }
  .logo { font-size: 24px; font-weight: 700; color: #4f46e5; }
  .logo span { color: #6366f1; }
  .invoice-title { text-align: right; }
  .invoice-title h1 { font-size: 28px; color: #4f46e5; font-weight: 300; letter-spacing: 2px; }
  .invoice-title .number { font-size: 14px; color: #64748b; margin-top: 4px; }
  .meta-grid { display: flex; gap: 40px; margin-bottom: 30px; }
  .meta-box { flex: 1; }
  .meta-box h3 { font-size: 10px; text-transform: uppercase; letter-spacing: 1px; color: #94a3b8; margin-bottom: 8px; }
  .meta-box p { font-size: 13px; }
  .meta-box .value { font-weight: 600; color: #1e293b; }
  table { width: 100%; border-collapse: collapse; margin: 20px 0; }
  thead th { background: #f1f5f9; padding: 12px 16px; text-align: left; font-size: 11px; text-transform: uppercase; letter-spacing: 0.5px; color: #475569; border-bottom: 2px solid #e2e8f0; }
  tbody td { padding: 14px 16px; border-bottom: 1px solid #e2e8f0; }
  .amount-col { text-align: right; }
  .totals { margin-left: auto; width: 280px; }
  .totals table { margin: 0; }
  .totals td { padding: 8px 16px; border: none; }
  .totals .label { color: #64748b; }
  .totals .amount { text-align: right; font-weight: 500; }
  .totals .grand-total { font-size: 16px; font-weight: 700; color: #4f46e5; border-top: 2px solid #4f46e5; }
  .totals .grand-total .amount { color: #4f46e5; }
  .footer { margin-top: 60px; padding-top: 20px; border-top: 1px solid #e2e8f0; }
  .footer-grid { display: flex; justify-content: space-between; }
  .footer-box { width: 48%; }
  .footer-box h4 { font-size: 10px; text-transform: uppercase; letter-spacing: 1px; color: #94a3b8; margin-bottom: 6px; }
  .footer-box p { font-size: 11px; color: #64748b; }
  .status-badge { display: inline-block; background: #dcfce7; color: #16a34a; padding: 4px 12px; border-radius: 20px; font-size: 11px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.5px; }
  .legal { margin-top: 30px; font-size: 10px; color: #94a3b8; text-align: center; }
</style>
</head>
<body>
<div class="page">
  <div class="header">
    <div class="logo">${appName}</div>
    <div class="invoice-title">
      <h1>INVOICE</h1>
      <div class="number">${invoice.invoice_number}</div>
    </div>
  </div>

  <div class="meta-grid">
    <div class="meta-box">
      <h3>Billed To</h3>
      <p class="value">${school.name}</p>
      <p>${[school.address, school.city, school.state, school.country].filter(Boolean).join(", ") || "—"}</p>
      ${school.gstin ? `<p style="margin-top:6px"><strong>GSTIN:</strong> ${school.gstin}</p>` : ""}
    </div>
    <div class="meta-box">
      <h3>Invoice Details</h3>
      <p><span class="label">Date:</span> ${invoiceDate}</p>
      <p><span class="label">Period:</span> ${periodStr}</p>
      <p><span class="label">Plan:</span> ${capitalize(invoice.plan_name)} (${capitalize(invoice.billing_period)})</p>
      <p style="margin-top:8px"><span class="status-badge">PAID</span></p>
    </div>
  </div>

  <table>
    <thead>
      <tr>
        <th style="width:50%">Description</th>
        <th class="amount-col">Amount</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>${capitalize(invoice.plan_name)} Plan – ${capitalize(invoice.billing_period)} subscription</td>
        <td class="amount-col">${fmt(invoice.amount)}</td>
      </tr>
    </tbody>
  </table>

  <div class="totals">
    <table>
      <tr>
        <td class="label">Subtotal</td>
        <td class="amount">${fmt(invoice.amount)}</td>
      </tr>
      ${
        Number(invoice.tax_amount) > 0
          ? `
      <tr>
        <td class="label">GST (18%)</td>
        <td class="amount">${fmt(invoice.tax_amount)}</td>
      </tr>`
          : ""
      }
      <tr class="grand-total">
        <td>Total Paid</td>
        <td class="amount">${fmt(invoice.total_amount)}</td>
      </tr>
    </table>
  </div>

  <div class="footer">
    <div class="footer-grid">
      <div class="footer-box">
        <h4>Payment Method</h4>
        <p>${capitalize(invoice.gateway || "Online Payment")}</p>
        ${invoice.gateway_invoice_id ? `<p>Transaction ID: ${invoice.gateway_invoice_id}</p>` : ""}
      </div>
      <div class="footer-box">
        <h4>From</h4>
        <p>${appName}</p>
        <p>${appUrl}</p>
        <p>CIN: U72900DL2024PTC000001</p>
      </div>
    </div>
    <div class="legal">
      This is a system-generated invoice. For billing queries contact billing@edusaas.in | This document serves as your official tax invoice under GST Act.
    </div>
  </div>
</div>
</body>
</html>`;

    try {
      const browser = await puppeteer.launch({
        headless: true,
        // Use system Chromium when PUPPETEER_EXECUTABLE_PATH is set (Docker/Alpine)
        executablePath: process.env.PUPPETEER_EXECUTABLE_PATH || undefined,
        args: [
          "--no-sandbox",
          "--disable-setuid-sandbox",
          "--disable-dev-shm-usage",   // Required in Docker: avoids /dev/shm OOM crashes
          "--disable-gpu",             // Not needed in headless mode
          "--no-zygote",               // Alpine/musl compatibility
          "--single-process",          // Reduces memory usage in containers
          "--disable-extensions",
          "--disable-background-networking",
        ],
      });
      const page = await browser.newPage();
      await page.setContent(html, { waitUntil: "networkidle0", timeout: 30000 });

      const fileName = `invoice-${invoice.invoice_number}.pdf`;
      const filePath = path.join(this.pdfDir, fileName);

      await page.pdf({
        path: filePath,
        format: "A4",
        margin: { top: "20px", right: "20px", bottom: "20px", left: "20px" },
      });

      await browser.close();

      return `/uploads/invoices/${fileName}`;
    } catch (err) {
      console.error("[InvoiceService] PDF generation error:", err);
      return null;
    }
  }

  // ─── Private helpers ────────────────────────────────────────

  private async sendReceiptEmail(school: any, invoice: any): Promise<void> {
    const appName = process.env.APP_NAME || "EduSaaS";
    const currency = invoice.currency || "INR";
    const fmt = (n: number) =>
      currency === "INR"
        ? `₹${Number(n).toLocaleString("en-IN", { minimumFractionDigits: 2 })}`
        : `${currency} ${Number(n).toFixed(2)}`;

    const periodStr = `${fmtDate(invoice.period_start)} – ${fmtDate(invoice.period_end)}`;
    const subject = `Payment receipt – ${invoice.invoice_number} | ${appName}`;

    const pdfAttachment = invoice.pdf_url
      ? `${process.env.APP_URL || "https://edusaas.in"}${invoice.pdf_url}`
      : null;

    const html = `
<!DOCTYPE html><html><head>
<style>
  body{font-family:Arial,sans-serif;line-height:1.6;color:#333;margin:0;padding:0}
  .wrap{max-width:620px;margin:0 auto;padding:20px}
  .header{background:linear-gradient(135deg,#4f46e5,#6366f1);color:white;padding:28px 32px;border-radius:12px 12px 0 0}
  .header h1{margin:0;font-size:22px}
  .header p{margin:4px 0 0;opacity:.85;font-size:14px}
  .body{background:#f8fafc;padding:28px 32px;border-radius:0 0 12px 12px}
  .badge{display:inline-block;background:#dcfce7;color:#16a34a;padding:4px 12px;border-radius:20px;font-size:12px;font-weight:600;margin-bottom:16px}
  table{width:100%;border-collapse:collapse;margin:16px 0}
  th{text-align:left;padding:10px 12px;background:#e2e8f0;font-size:13px;color:#475569}
  td{padding:10px 12px;border-bottom:1px solid #e2e8f0;font-size:14px}
  .total-row td{font-weight:700;background:#f1f5f9;font-size:15px}
  .school-box{background:white;border:1px solid #e2e8f0;border-radius:8px;padding:14px 18px;margin-top:20px;font-size:13px;color:#475569}
  .footer{text-align:center;margin-top:20px;font-size:12px;color:#94a3b8}
  .btn{display:inline-block;background:#4f46e5;color:white;padding:12px 24px;text-decoration:none;border-radius:8px;font-weight:600;margin-top:16px}
</style>
</head><body><div class="wrap">
  <div class="header">
    <h1>${appName}</h1>
    <p>Payment Receipt</p>
  </div>
  <div class="body">
    <div class="badge">PAID</div>
    <p>Hi ${school.name},<br>Thank you for your payment. Here is your receipt.</p>

    <table>
      <tr><th>Invoice #</th><td>${invoice.invoice_number}</td></tr>
      <tr><th>Date</th><td>${fmtDate(invoice.paid_at || invoice.created_at)}</td></tr>
      <tr><th>Plan</th><td>${capitalize(invoice.plan_name)} (${invoice.billing_period})</td></tr>
      <tr><th>Period</th><td>${periodStr}</td></tr>
    </table>

    <table>
      <tr><th>Description</th><th style="text-align:right">Amount</th></tr>
      <tr>
        <td>${capitalize(invoice.plan_name)} Plan – ${capitalize(invoice.billing_period)} subscription</td>
        <td style="text-align:right">${fmt(invoice.amount)}</td>
      </tr>
      ${
        Number(invoice.tax_amount) > 0
          ? `
      <tr>
        <td>GST (18%)</td>
        <td style="text-align:right">${fmt(invoice.tax_amount)}</td>
      </tr>`
          : ""
      }
      <tr class="total-row">
        <td>Total Paid</td>
        <td style="text-align:right">${fmt(invoice.total_amount)}</td>
      </tr>
    </table>

    <div class="school-box">
      <strong>Billed to:</strong><br>
      ${school.name}<br>
      ${[school.address, school.city, school.state, school.country].filter(Boolean).join(", ")}
      ${school.gstin ? `<br><strong>GSTIN:</strong> ${school.gstin}` : ""}
    </div>

    ${
      pdfAttachment
        ? `
    <a href="${pdfAttachment}" class="btn">Download PDF Invoice</a>
    `
        : ""
    }

    <p style="margin-top:20px;font-size:13px;color:#64748b">
      Keep this email as your official receipt. For billing queries write to
      <a href="mailto:billing@edusaas.in">billing@edusaas.in</a>.
    </p>
  </div>
  <div class="footer">© ${new Date().getFullYear()} ${appName}. All rights reserved.</div>
</div></body></html>`;

    await emailService.sendEmail({ to: school.email, subject, html });
  }
}

// ─── Tiny helpers ────────────────────────────────────────────

function fmtDate(d: Date | string | null): string {
  if (!d) return "—";
  return new Date(d).toLocaleDateString("en-IN", {
    day: "2-digit",
    month: "short",
    year: "numeric",
  });
}

function capitalize(s: string): string {
  if (!s) return "";
  return s.charAt(0).toUpperCase() + s.slice(1);
}

export const invoiceService = new InvoiceService();
